# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\all_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 749)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_weather = QtWidgets.QLabel(self.centralwidget)
        self.label_weather.setGeometry(QtCore.QRect(20, 0, 100, 40))
        self.label_weather.setStyleSheet("background-color: rgb(135, 137, 255);\n"
"font: 12pt \"Arial\";")
        self.label_weather.setObjectName("label_weather")
        self.label_movie = QtWidgets.QLabel(self.centralwidget)
        self.label_movie.setGeometry(QtCore.QRect(240, 80, 100, 40))
        self.label_movie.setStyleSheet("background-color: rgb(135, 137, 255);\n"
"font: 12pt \"Arial\";")
        self.label_movie.setObjectName("label_movie")
        self.label_best = QtWidgets.QLabel(self.centralwidget)
        self.label_best.setGeometry(QtCore.QRect(510, 80, 120, 40))
        self.label_best.setStyleSheet("background-color: rgb(135, 137, 255);\n"
"font: 12pt \"Arial\";")
        self.label_best.setObjectName("label_best")
        self.text_weather = QtWidgets.QLabel(self.centralwidget)
        self.text_weather.setGeometry(QtCore.QRect(10, 20, 170, 500))
        self.text_weather.setStyleSheet("font: 12pt \"Arial\";\n"
"background-color: rgb(232, 229, 255);")
        self.text_weather.setText("")
        self.text_weather.setWordWrap(True)
        self.text_weather.setObjectName("text_weather")
        self.text_best = QtWidgets.QLabel(self.centralwidget)
        self.text_best.setGeometry(QtCore.QRect(500, 100, 370, 370))
        self.text_best.setStyleSheet("font: 11pt \"Arial\";\n"
"background-color: rgb(255, 255, 255);")
        self.text_best.setText("")
        self.text_best.setWordWrap(True)
        self.text_best.setObjectName("text_best")
        self.text_movie = QtWidgets.QLabel(self.centralwidget)
        self.text_movie.setGeometry(QtCore.QRect(230, 100, 250, 370))
        self.text_movie.setStyleSheet("font: 11pt \"Arial\";\n"
"background-color: rgb(255, 255, 255);")
        self.text_movie.setText("")
        self.text_movie.setWordWrap(True)
        self.text_movie.setObjectName("text_movie")
        self.text_10 = QtWidgets.QLabel(self.centralwidget)
        self.text_10.setGeometry(QtCore.QRect(210, 40, 680, 700))
        self.text_10.setStyleSheet("background-color: rgb(232, 229, 255);")
        self.text_10.setText("")
        self.text_10.setObjectName("text_10")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(220, 20, 100, 40))
        self.label_10.setStyleSheet("background-color: rgb(135, 137, 255);\n"
"font: 12pt \"Arial\";")
        self.label_10.setObjectName("label_10")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(0, 520, 200, 200))
        self.pushButton.setStyleSheet("border-image: url(:/newPrefix/map.jpg);")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.text_baekjoon = QtWidgets.QLabel(self.centralwidget)
        self.text_baekjoon.setGeometry(QtCore.QRect(230, 510, 320, 180))
        self.text_baekjoon.setStyleSheet("font: 11pt \"Arial\";\n"
"background-color: rgb(255, 255, 255);")
        self.text_baekjoon.setText("")
        self.text_baekjoon.setWordWrap(True)
        self.text_baekjoon.setObjectName("text_baekjoon")
        self.label_baekjoon = QtWidgets.QLabel(self.centralwidget)
        self.label_baekjoon.setGeometry(QtCore.QRect(240, 490, 120, 40))
        self.label_baekjoon.setStyleSheet("background-color: rgb(135, 137, 255);\n"
"font: 12pt \"Arial\";")
        self.label_baekjoon.setObjectName("label_baekjoon")
        self.text_baekjoon_2 = QtWidgets.QLabel(self.centralwidget)
        self.text_baekjoon_2.setGeometry(QtCore.QRect(550, 510, 320, 180))
        self.text_baekjoon_2.setStyleSheet("font: 11pt \"Arial\";\n"
"background-color: rgb(255, 255, 255);")
        self.text_baekjoon_2.setText("")
        self.text_baekjoon_2.setWordWrap(True)
        self.text_baekjoon_2.setObjectName("text_baekjoon_2")
        self.pushButton.raise_()
        self.text_10.raise_()
        self.text_weather.raise_()
        self.text_best.raise_()
        self.text_movie.raise_()
        self.label_weather.raise_()
        self.label_best.raise_()
        self.label_movie.raise_()
        self.label_10.raise_()
        self.text_baekjoon.raise_()
        self.label_baekjoon.raise_()
        self.text_baekjoon_2.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 900, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_weather.setText(_translate("MainWindow", "Weather"))
        self.label_movie.setText(_translate("MainWindow", "Movie"))
        self.label_best.setText(_translate("MainWindow", "Book"))
        self.label_10.setText(_translate("MainWindow", "Top 10"))
        self.label_baekjoon.setText(_translate("MainWindow", "Music"))
import image_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
